replicas: 1
maxSurge: 1
maxUnavailable: 1

env: minikube

databaseConfig: |
  - name: DB_HOST
    value: $(POSTGRES_SERVICE_HOST)
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: db-config
        key: db-port
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-config
        key: db-name
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password

service:
  port: 8084
  type: ClusterIP
containerPort: 8084

resources:
  requests:
    memory: "512Mi"