services:
 postgres:
  container_name: postgres-it
  image: sdcplatform/ras-rm-docker-postgres
  ports:
   - "15432:5432"
 pubsub-emulator:
   container_name: pubsub-emulator-it
   image: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images/pubsub-emulator
   ports:
     - "18681:8681"
   environment:
     - PUBSUB_PROJECT1=test,test_topic:test_subscription,sample_unit_topic:sample_unit_subscription,event_status_topic:event_status_subscription
 survey:
   container_name: survey-it
   image: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images/survey
   ports:
    - "18080:8080"
   external_links:
    - postgres-it
   environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres-it:5432/postgres?sslmode=disable
    - security_user_name=admin
    - security_user_password=secret

 wiremock:
   container_name: wiremock-collex-it
   image: wiremock/wiremock:3.13.0
   ports:
     - "18002:8080"
   environment:
     - WIREMOCK_PORT=8080
     - WIREMOCK_HOST=wiremock-collex-it
     - WIREMOCK_URL=http://wiremock-collex-it:18002/__admin/mappings