version: '2'
services:
 postgres:
  container_name: postgres-it
  image: sdcplatform/ras-rm-docker-postgres
  ports:
   - "15432:5432"
 redis:
  container_name: redis-it
  image: redis:3.2.9
  ports:
   - "17379:6379"
 pubsub-emulator:
   container_name: pubsub-emulator-it
   image: eu.gcr.io/ons-rasrmbs-management/pubsub-emulator
   ports:
     - "18681:8681"
   environment:
     - PUBSUB_PROJECT1=test,sample_unit_topic:sample_unit_subscription,event_status_topic:event_status_subscription
 survey:
   container_name: survey-it
   image: eu.gcr.io/ons-rasrmbs-management/survey
   ports:
    - "18080:8080"
   external_links:
    - postgres-it
   environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres-it:5432/postgres?sslmode=disable
    - security_user_name=admin
    - security_user_password=secret