version: '2'
services:
 postgres:
  container_name: postgres
  image: sdcplatform/ras-rm-docker-postgres
  ports:
   - "6432:5432"
 redis:
  container_name: redis
  image: redis:3.2.9
  ports:
   - "7379:6379"
 rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:3.6.10-management
  ports:
    - "5369:4369"
    - "45672:25672"
    - "6671:5671"
    - "6672:5672"
    - "16671:15671"
    - "16672:15672"
 sftp:
    container_name: sftp
    image: atmoz/sftp
    volumes:
        - ~/Documents/sftp:/home/centos/Documents/sftp
    ports:
        - "122:22"
    command: centos:JLibV2&XD,:1001
 survey:
   container_name: survey
   image: sdcplatform/surveysvc
   ports:
    - "8080:8080"
   external_links:
    - postgres
   environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    - security_user_name=admin
    - security_user_password=secret

