env: minikube
namespace: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

crons:
  distributeSampleUnit:
    name: collection-exercise-sample-unit-distribution
    cron: "* * * * *"
    target: "cron/sample-unit-distribution"
  validateSampleUnit:
    name: collection-exercise-sample-unit-validation
    cron: "* * * * *"
    target: "cron/sample-unit-validation"
  executeEvents:
    name: collection-exercise-execute-events
    cron: "* * * * *"
    target: "cron/execute-scheduled-events"

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "500Mi"
    cpu: "25m"
  limits:
    memory: "1000Mi"
    cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 200
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

managedRabbitMQ:
  enabled: false

tomcat:
  initialSize: 5
  maxActive: 10
  maxIdle: 5
  minIdle: 3

dns:
  enabled: false
  wellKnownPort: 8080

deprecateAction: false