env: minikube
namespace: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

crons:
  processEvents:
    name: collection-exercise-process-events
    cron: "* * * * *"
    target: "cron/process-scheduled-events"

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "500Mi"
      cpu: "200m"
    limits:
      memory: "700Mi"
      cpu: "650m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 500
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

tomcat:
  initialSize: 5
  maxActive: 10
  maxIdle: 5
  minIdle: 3

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: ras-rm-sandbox
  caseNotificationTopic: "case-notification-topic"
  sampleSummaryActivationStatusSubscription: sample-summary-activation-status
  sampleSummaryActivationTopic: sample-summary-activation
