env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

crons:
  distributeSampleUnit:
    name: collection-exercise-sample-unit-distribution
    cron: "* * * * *"
    target: "cron/sample-unit-distribution"
  validateSampleUnit:
    name: collection-exercise-sample-unit-validation
    cron: "* * * * *"
    target: "cron/sample-unit-validation"
  executeEvents:
    name: collection-exercise-execute-events
    cron: "* * * * *"
    target: "cron/execute-events"

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "512Mi"

managedRabbitMQ:
  enabled: false

tomcat:
  initialSize: 5
  maxActive: 10
  maxIdle: 5
  minIdle: 3

dns:
  enabled: false
  wellKnownPort: 8080

deprecateAction: false