//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.05.02 at 11:51:09 PM BST
//

package uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import java.util.*;
import javax.xml.bind.annotation.*;

/**
 * Java class for SampleUnit complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SampleUnit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sampleUnitRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sampleUnitType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="collectionExerciseId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sampleAttributes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "SampleUnit",
    propOrder = {
      "id",
      "sampleUnitRef",
      "sampleUnitType",
      "formType",
      "collectionExerciseId",
      "sampleAttributes"
    })
@XmlRootElement(name = "sampleUnit")
public class SampleUnit {

  protected String id;

  @XmlElement(required = true)
  protected String sampleUnitRef;

  @XmlElement(required = true)
  protected String sampleUnitType;

  protected String formType;

  @XmlElement(required = true)
  protected String collectionExerciseId;

  protected uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
          .SampleAttributes
      sampleAttributes;

  /** Default no-arg constructor */
  public SampleUnit() {
    super();
  }

  /** Fully-initialising value constructor */
  public SampleUnit(
      final String id,
      final String sampleUnitRef,
      final String sampleUnitType,
      final String formType,
      final String collectionExerciseId,
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          sampleAttributes) {
    this.id = id;
    this.sampleUnitRef = sampleUnitRef;
    this.sampleUnitType = sampleUnitType;
    this.formType = formType;
    this.collectionExerciseId = collectionExerciseId;
    this.sampleAttributes = sampleAttributes;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the sampleUnitRef property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUnitRef() {
    return sampleUnitRef;
  }

  /**
   * Sets the value of the sampleUnitRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUnitRef(String value) {
    this.sampleUnitRef = value;
  }

  /**
   * Gets the value of the sampleUnitType property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUnitType() {
    return sampleUnitType;
  }

  /**
   * Sets the value of the sampleUnitType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUnitType(String value) {
    this.sampleUnitType = value;
  }

  /**
   * Gets the value of the formType property.
   *
   * @return possible object is {@link String }
   */
  public String getFormType() {
    return formType;
  }

  /**
   * Sets the value of the formType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFormType(String value) {
    this.formType = value;
  }

  /**
   * Gets the value of the collectionExerciseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCollectionExerciseId() {
    return collectionExerciseId;
  }

  /**
   * Sets the value of the collectionExerciseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCollectionExerciseId(String value) {
    this.collectionExerciseId = value;
  }

  /**
   * Gets the value of the sampleAttributes property.
   *
   * @return possible object is {@link
   *     uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes
   *     }
   */
  public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
          .SampleAttributes
      getSampleAttributes() {
    return sampleAttributes;
  }

  /**
   * Sets the value of the sampleAttributes property.
   *
   * @param value allowed object is {@link
   *     uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes
   *     }
   */
  public void setSampleAttributes(
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          value) {
    this.sampleAttributes = value;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method
   * and should not be called directly by client code.
   *
   * @param _other A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .Builder<
              _B>
          _other) {
    _other.id = this.id;
    _other.sampleUnitRef = this.sampleUnitRef;
    _other.sampleUnitType = this.sampleUnitType;
    _other.formType = this.formType;
    _other.collectionExerciseId = this.collectionExerciseId;
    _other.sampleAttributes =
        ((this.sampleAttributes == null) ? null : this.sampleAttributes.newCopyBuilder(_other));
  }

  public <_B>
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<_B>
          newCopyBuilder(final _B _parentBuilder) {
    return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            .Builder<
        _B>(_parentBuilder, this, true);
  }

  public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
          Void>
      newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .Builder<
          Void>
      builder() {
    return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            .Builder<
        Void>(null, null, false);
  }

  public static <_B>
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<_B>
          copyOf(
              final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  _other) {
    final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        _newBuilder =
            new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Builder<
                _B>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method
   * and should not be called directly by client code.
   *
   * @param _other A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .Builder<
              _B>
          _other,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse) {
    final PropertyTree idPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("id"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (idPropertyTree != null)
        : ((idPropertyTree == null) || (!idPropertyTree.isLeaf())))) {
      _other.id = this.id;
    }
    final PropertyTree sampleUnitRefPropertyTree =
        ((_propertyTree == null) ? null : _propertyTree.get("sampleUnitRef"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (sampleUnitRefPropertyTree != null)
        : ((sampleUnitRefPropertyTree == null) || (!sampleUnitRefPropertyTree.isLeaf())))) {
      _other.sampleUnitRef = this.sampleUnitRef;
    }
    final PropertyTree sampleUnitTypePropertyTree =
        ((_propertyTree == null) ? null : _propertyTree.get("sampleUnitType"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (sampleUnitTypePropertyTree != null)
        : ((sampleUnitTypePropertyTree == null) || (!sampleUnitTypePropertyTree.isLeaf())))) {
      _other.sampleUnitType = this.sampleUnitType;
    }
    final PropertyTree formTypePropertyTree =
        ((_propertyTree == null) ? null : _propertyTree.get("formType"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (formTypePropertyTree != null)
        : ((formTypePropertyTree == null) || (!formTypePropertyTree.isLeaf())))) {
      _other.formType = this.formType;
    }
    final PropertyTree collectionExerciseIdPropertyTree =
        ((_propertyTree == null) ? null : _propertyTree.get("collectionExerciseId"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (collectionExerciseIdPropertyTree != null)
        : ((collectionExerciseIdPropertyTree == null)
            || (!collectionExerciseIdPropertyTree.isLeaf())))) {
      _other.collectionExerciseId = this.collectionExerciseId;
    }
    final PropertyTree sampleAttributesPropertyTree =
        ((_propertyTree == null) ? null : _propertyTree.get("sampleAttributes"));
    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
        ? (sampleAttributesPropertyTree != null)
        : ((sampleAttributesPropertyTree == null) || (!sampleAttributesPropertyTree.isLeaf())))) {
      _other.sampleAttributes =
          ((this.sampleAttributes == null)
              ? null
              : this.sampleAttributes.newCopyBuilder(
                  _other, sampleAttributesPropertyTree, _propertyTreeUse));
    }
  }

  public <_B>
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<_B>
          newCopyBuilder(
              final _B _parentBuilder,
              final PropertyTree _propertyTree,
              final PropertyTreeUse _propertyTreeUse) {
    return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            .Builder<
        _B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
          Void>
      newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B>
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<_B>
          copyOf(
              final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  _other,
              final PropertyTree _propertyTree,
              final PropertyTreeUse _propertyTreeUse) {
    final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        _newBuilder =
            new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Builder<
                _B>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .Builder<
          Void>
      copyExcept(
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              _other,
          final PropertyTree _propertyTree) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .Builder<
          Void>
      copyOnly(
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              _other,
          final PropertyTree _propertyTree) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public boolean equals(Object object) {
    if ((object == null) || (this.getClass() != object.getClass())) {
      return false;
    }
    if (this == object) {
      return true;
    }
    final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit that =
        ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit) object);
    {
      String leftId;
      leftId = this.getId();
      String rightId;
      rightId = that.getId();
      if (this.id != null) {
        if (that.id != null) {
          if (!leftId.equals(rightId)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.id != null) {
          return false;
        }
      }
    }
    {
      String leftSampleUnitRef;
      leftSampleUnitRef = this.getSampleUnitRef();
      String rightSampleUnitRef;
      rightSampleUnitRef = that.getSampleUnitRef();
      if (this.sampleUnitRef != null) {
        if (that.sampleUnitRef != null) {
          if (!leftSampleUnitRef.equals(rightSampleUnitRef)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.sampleUnitRef != null) {
          return false;
        }
      }
    }
    {
      String leftSampleUnitType;
      leftSampleUnitType = this.getSampleUnitType();
      String rightSampleUnitType;
      rightSampleUnitType = that.getSampleUnitType();
      if (this.sampleUnitType != null) {
        if (that.sampleUnitType != null) {
          if (!leftSampleUnitType.equals(rightSampleUnitType)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.sampleUnitType != null) {
          return false;
        }
      }
    }
    {
      String leftFormType;
      leftFormType = this.getFormType();
      String rightFormType;
      rightFormType = that.getFormType();
      if (this.formType != null) {
        if (that.formType != null) {
          if (!leftFormType.equals(rightFormType)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.formType != null) {
          return false;
        }
      }
    }
    {
      String leftCollectionExerciseId;
      leftCollectionExerciseId = this.getCollectionExerciseId();
      String rightCollectionExerciseId;
      rightCollectionExerciseId = that.getCollectionExerciseId();
      if (this.collectionExerciseId != null) {
        if (that.collectionExerciseId != null) {
          if (!leftCollectionExerciseId.equals(rightCollectionExerciseId)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.collectionExerciseId != null) {
          return false;
        }
      }
    }
    {
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          leftSampleAttributes;
      leftSampleAttributes = this.getSampleAttributes();
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          rightSampleAttributes;
      rightSampleAttributes = that.getSampleAttributes();
      if (this.sampleAttributes != null) {
        if (that.sampleAttributes != null) {
          if (!leftSampleAttributes.equals(rightSampleAttributes)) {
            return false;
          }
        } else {
          return false;
        }
      } else {
        if (that.sampleAttributes != null) {
          return false;
        }
      }
    }
    return true;
  }

  public int hashCode() {
    int currentHashCode = 1;
    {
      currentHashCode = (currentHashCode * 31);
      String theId;
      theId = this.getId();
      if (this.id != null) {
        currentHashCode += theId.hashCode();
      }
    }
    {
      currentHashCode = (currentHashCode * 31);
      String theSampleUnitRef;
      theSampleUnitRef = this.getSampleUnitRef();
      if (this.sampleUnitRef != null) {
        currentHashCode += theSampleUnitRef.hashCode();
      }
    }
    {
      currentHashCode = (currentHashCode * 31);
      String theSampleUnitType;
      theSampleUnitType = this.getSampleUnitType();
      if (this.sampleUnitType != null) {
        currentHashCode += theSampleUnitType.hashCode();
      }
    }
    {
      currentHashCode = (currentHashCode * 31);
      String theFormType;
      theFormType = this.getFormType();
      if (this.formType != null) {
        currentHashCode += theFormType.hashCode();
      }
    }
    {
      currentHashCode = (currentHashCode * 31);
      String theCollectionExerciseId;
      theCollectionExerciseId = this.getCollectionExerciseId();
      if (this.collectionExerciseId != null) {
        currentHashCode += theCollectionExerciseId.hashCode();
      }
    }
    {
      currentHashCode = (currentHashCode * 31);
      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          theSampleAttributes;
      theSampleAttributes = this.getSampleAttributes();
      if (this.sampleAttributes != null) {
        currentHashCode += theSampleAttributes.hashCode();
      }
    }
    return currentHashCode;
  }

  public static class Builder<_B> implements Buildable {

    protected final _B _parentBuilder;
    protected final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
        _storedValue;
    private String id;
    private String sampleUnitRef;
    private String sampleUnitType;
    private String formType;
    private String collectionExerciseId;
    private uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Builder<
                _B>>
        sampleAttributes;

    public Builder(
        final _B _parentBuilder,
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            _other,
        final boolean _copy) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          this.id = _other.id;
          this.sampleUnitRef = _other.sampleUnitRef;
          this.sampleUnitType = _other.sampleUnitType;
          this.formType = _other.formType;
          this.collectionExerciseId = _other.collectionExerciseId;
          this.sampleAttributes =
              ((_other.sampleAttributes == null)
                  ? null
                  : _other.sampleAttributes.newCopyBuilder(this));
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public Builder(
        final _B _parentBuilder,
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            _other,
        final boolean _copy,
        final PropertyTree _propertyTree,
        final PropertyTreeUse _propertyTreeUse) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          final PropertyTree idPropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("id"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (idPropertyTree != null)
              : ((idPropertyTree == null) || (!idPropertyTree.isLeaf())))) {
            this.id = _other.id;
          }
          final PropertyTree sampleUnitRefPropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("sampleUnitRef"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (sampleUnitRefPropertyTree != null)
              : ((sampleUnitRefPropertyTree == null) || (!sampleUnitRefPropertyTree.isLeaf())))) {
            this.sampleUnitRef = _other.sampleUnitRef;
          }
          final PropertyTree sampleUnitTypePropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("sampleUnitType"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (sampleUnitTypePropertyTree != null)
              : ((sampleUnitTypePropertyTree == null) || (!sampleUnitTypePropertyTree.isLeaf())))) {
            this.sampleUnitType = _other.sampleUnitType;
          }
          final PropertyTree formTypePropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("formType"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (formTypePropertyTree != null)
              : ((formTypePropertyTree == null) || (!formTypePropertyTree.isLeaf())))) {
            this.formType = _other.formType;
          }
          final PropertyTree collectionExerciseIdPropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("collectionExerciseId"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (collectionExerciseIdPropertyTree != null)
              : ((collectionExerciseIdPropertyTree == null)
                  || (!collectionExerciseIdPropertyTree.isLeaf())))) {
            this.collectionExerciseId = _other.collectionExerciseId;
          }
          final PropertyTree sampleAttributesPropertyTree =
              ((_propertyTree == null) ? null : _propertyTree.get("sampleAttributes"));
          if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (sampleAttributesPropertyTree != null)
              : ((sampleAttributesPropertyTree == null)
                  || (!sampleAttributesPropertyTree.isLeaf())))) {
            this.sampleAttributes =
                ((_other.sampleAttributes == null)
                    ? null
                    : _other.sampleAttributes.newCopyBuilder(
                        this, sampleAttributesPropertyTree, _propertyTreeUse));
          }
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public _B end() {
      return this._parentBuilder;
    }

    protected <
            _P extends
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit>
        _P init(final _P _product) {
      _product.id = this.id;
      _product.sampleUnitRef = this.sampleUnitRef;
      _product.sampleUnitType = this.sampleUnitType;
      _product.formType = this.formType;
      _product.collectionExerciseId = this.collectionExerciseId;
      _product.sampleAttributes =
          ((this.sampleAttributes == null) ? null : this.sampleAttributes.build());
      return _product;
    }

    /**
     * Sets the new value of "id" (any previous value will be replaced)
     *
     * @param id New value of the "id" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withId(final String id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the new value of "sampleUnitRef" (any previous value will be replaced)
     *
     * @param sampleUnitRef New value of the "sampleUnitRef" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withSampleUnitRef(final String sampleUnitRef) {
      this.sampleUnitRef = sampleUnitRef;
      return this;
    }

    /**
     * Sets the new value of "sampleUnitType" (any previous value will be replaced)
     *
     * @param sampleUnitType New value of the "sampleUnitType" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withSampleUnitType(final String sampleUnitType) {
      this.sampleUnitType = sampleUnitType;
      return this;
    }

    /**
     * Sets the new value of "formType" (any previous value will be replaced)
     *
     * @param formType New value of the "formType" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withFormType(final String formType) {
      this.formType = formType;
      return this;
    }

    /**
     * Sets the new value of "collectionExerciseId" (any previous value will be replaced)
     *
     * @param collectionExerciseId New value of the "collectionExerciseId" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withCollectionExerciseId(final String collectionExerciseId) {
      this.collectionExerciseId = collectionExerciseId;
      return this;
    }

    /**
     * Sets the new value of "sampleAttributes" (any previous value will be replaced)
     *
     * @param sampleAttributes New value of the "sampleAttributes" property.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Builder<
            _B>
        withSampleAttributes(
            final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes
                sampleAttributes) {
      this.sampleAttributes =
          ((sampleAttributes == null)
              ? null
              : new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Builder<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Builder<
                      _B>>(this, sampleAttributes, false));
      return this;
    }

    /**
     * Returns a new builder to build the value of the "sampleAttributes" property (replacing
     * previous value). Use {@link
     * uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes.Builder#end()}
     * to return to the current builder.
     *
     * @return A new builder to build the value of the "sampleAttributes" property. Use {@link
     *     uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes.Builder#end()}
     *     to return to the current builder.
     */
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            ? extends
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .Builder<
                    _B>>
        withSampleAttributes() {
      return this.sampleAttributes =
          new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .Builder<
                  _B>>(this, null, false);
    }

    @Override
    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
        build() {
      if (_storedValue == null) {
        return this.init(
            new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit());
      } else {
        return ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit)
            _storedValue);
      }
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"entries"})
  public static class SampleAttributes {

    @XmlElement(name = "entry")
    protected List<
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry>
        entries;

    /** Default no-arg constructor */
    public SampleAttributes() {
      super();
    }

    /** Fully-initialising value constructor */
    public SampleAttributes(
        final List<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry>
            entries) {
      this.entries = entries;
    }

    /**
     * Gets the value of the entries property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the entries property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getEntries().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes.Entry
     * }
     */
    public List<
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry>
        getEntries() {
      if (entries == null) {
        entries =
            new ArrayList<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry>();
      }
      return this.entries;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf}
     * method and should not be called directly by client code.
     *
     * @param _other A builder instance to which the state of this object will be copied.
     */
    public <_B> void copyTo(
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            _other) {
      if (this.entries == null) {
        _other.entries = null;
      } else {
        _other.entries =
            new ArrayList<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Builder<
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Builder<
                        _B>>>();
        for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry
            _item : this.entries) {
          _other.entries.add(((_item == null) ? null : _item.newCopyBuilder(_other)));
        }
      }
    }

    public <_B>
        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            newCopyBuilder(final _B _parentBuilder) {
      return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes.Builder<
          _B>(_parentBuilder, this, true);
    }

    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            Void>
        newCopyBuilder() {
      return newCopyBuilder(null);
    }

    public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            Void>
        builder() {
      return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes.Builder<
          Void>(null, null, false);
    }

    public static <_B>
        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            copyOf(
                final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                        .SampleUnit.SampleAttributes
                    _other) {
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          _newBuilder =
              new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Builder<
                  _B>(null, null, false);
      _other.copyTo(_newBuilder);
      return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf}
     * method and should not be called directly by client code.
     *
     * @param _other A builder instance to which the state of this object will be copied.
     */
    public <_B> void copyTo(
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            _other,
        final PropertyTree _propertyTree,
        final PropertyTreeUse _propertyTreeUse) {
      final PropertyTree entriesPropertyTree =
          ((_propertyTree == null) ? null : _propertyTree.get("entries"));
      if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (entriesPropertyTree != null)
          : ((entriesPropertyTree == null) || (!entriesPropertyTree.isLeaf())))) {
        if (this.entries == null) {
          _other.entries = null;
        } else {
          _other.entries =
              new ArrayList<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Entry.Builder<
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Builder<
                          _B>>>();
          for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry
              _item : this.entries) {
            _other.entries.add(
                ((_item == null)
                    ? null
                    : _item.newCopyBuilder(_other, entriesPropertyTree, _propertyTreeUse)));
          }
        }
      }
    }

    public <_B>
        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            newCopyBuilder(
                final _B _parentBuilder,
                final PropertyTree _propertyTree,
                final PropertyTreeUse _propertyTreeUse) {
      return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes.Builder<
          _B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            Void>
        newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
      return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static <_B>
        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Builder<
                _B>
            copyOf(
                final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                        .SampleUnit.SampleAttributes
                    _other,
                final PropertyTree _propertyTree,
                final PropertyTreeUse _propertyTreeUse) {
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          _newBuilder =
              new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Builder<
                  _B>(null, null, false);
      _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
      return _newBuilder;
    }

    public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            Void>
        copyExcept(
            final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes
                _other,
            final PropertyTree _propertyTree) {
      return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Builder<
            Void>
        copyOnly(
            final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes
                _other,
            final PropertyTree _propertyTree) {
      return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public boolean equals(Object object) {
      if ((object == null) || (this.getClass() != object.getClass())) {
        return false;
      }
      if (this == object) {
        return true;
      }
      final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          that =
              ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes)
                  object);
      {
        List<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry>
            leftEntries;
        leftEntries =
            (((this.entries != null) && (!this.entries.isEmpty())) ? this.getEntries() : null);
        List<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry>
            rightEntries;
        rightEntries =
            (((that.entries != null) && (!that.entries.isEmpty())) ? that.getEntries() : null);
        if ((this.entries != null) && (!this.entries.isEmpty())) {
          if ((that.entries != null) && (!that.entries.isEmpty())) {
            if (!leftEntries.equals(rightEntries)) {
              return false;
            }
          } else {
            return false;
          }
        } else {
          if ((that.entries != null) && (!that.entries.isEmpty())) {
            return false;
          }
        }
      }
      return true;
    }

    public int hashCode() {
      int currentHashCode = 1;
      {
        currentHashCode = (currentHashCode * 31);
        List<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry>
            theEntries;
        theEntries =
            (((this.entries != null) && (!this.entries.isEmpty())) ? this.getEntries() : null);
        if ((this.entries != null) && (!this.entries.isEmpty())) {
          currentHashCode += theEntries.hashCode();
        }
      }
      return currentHashCode;
    }

    public static class Builder<_B> implements Buildable {

      protected final _B _parentBuilder;
      protected final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
              .SampleUnit.SampleAttributes
          _storedValue;
      private List<
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Builder<
                      _B>>>
          entries;

      public Builder(
          final _B _parentBuilder,
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes
              _other,
          final boolean _copy) {
        this._parentBuilder = _parentBuilder;
        if (_other != null) {
          if (_copy) {
            _storedValue = null;
            if (_other.entries == null) {
              this.entries = null;
            } else {
              this.entries =
                  new ArrayList<
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Entry.Builder<
                          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                                  .SampleUnit.SampleAttributes.Builder<
                              _B>>>();
              for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry
                  _item : _other.entries) {
                this.entries.add(((_item == null) ? null : _item.newCopyBuilder(this)));
              }
            }
          } else {
            _storedValue = _other;
          }
        } else {
          _storedValue = null;
        }
      }

      public Builder(
          final _B _parentBuilder,
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes
              _other,
          final boolean _copy,
          final PropertyTree _propertyTree,
          final PropertyTreeUse _propertyTreeUse) {
        this._parentBuilder = _parentBuilder;
        if (_other != null) {
          if (_copy) {
            _storedValue = null;
            final PropertyTree entriesPropertyTree =
                ((_propertyTree == null) ? null : _propertyTree.get("entries"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (entriesPropertyTree != null)
                : ((entriesPropertyTree == null) || (!entriesPropertyTree.isLeaf())))) {
              if (_other.entries == null) {
                this.entries = null;
              } else {
                this.entries =
                    new ArrayList<
                        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                                .SampleUnit.SampleAttributes.Entry.Builder<
                            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                                    .SampleUnit.SampleAttributes.Builder<
                                _B>>>();
                for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                        .SampleUnit.SampleAttributes.Entry
                    _item : _other.entries) {
                  this.entries.add(
                      ((_item == null)
                          ? null
                          : _item.newCopyBuilder(this, entriesPropertyTree, _propertyTreeUse)));
                }
              }
            }
          } else {
            _storedValue = _other;
          }
        } else {
          _storedValue = null;
        }
      }

      public _B end() {
        return this._parentBuilder;
      }

      protected <
              _P extends
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes>
          _P init(final _P _product) {
        if (this.entries != null) {
          final List<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry>
              entries =
                  new ArrayList<
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                          .SampleUnit.SampleAttributes.Entry>(this.entries.size());
          for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Builder<
                      _B>>
              _item : this.entries) {
            entries.add(_item.build());
          }
          _product.entries = entries;
        }
        return _product;
      }

      /**
       * Adds the given items to the value of "entries"
       *
       * @param entries Items to add to the value of the "entries" property
       */
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          addEntries(
              final Iterable<
                      ? extends
                          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Entry>
                  entries) {
        if (entries != null) {
          if (this.entries == null) {
            this.entries =
                new ArrayList<
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Entry.Builder<
                        uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                                .SampleUnit.SampleAttributes.Builder<
                            _B>>>();
          }
          for (uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry
              _item : entries) {
            this.entries.add(
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Builder<
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Builder<
                        _B>>(this, _item, false));
          }
        }
        return this;
      }

      /**
       * Sets the new value of "entries" (any previous value will be replaced)
       *
       * @param entries New value of the "entries" property.
       */
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          withEntries(
              final Iterable<
                      ? extends
                          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Entry>
                  entries) {
        if (this.entries != null) {
          this.entries.clear();
        }
        return addEntries(entries);
      }

      /**
       * Adds the given items to the value of "entries"
       *
       * @param entries Items to add to the value of the "entries" property
       */
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          addEntries(
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Entry
                      ...
                  entries) {
        addEntries(Arrays.asList(entries));
        return this;
      }

      /**
       * Sets the new value of "entries" (any previous value will be replaced)
       *
       * @param entries New value of the "entries" property.
       */
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Builder<
              _B>
          withEntries(
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Entry
                      ...
                  entries) {
        withEntries(Arrays.asList(entries));
        return this;
      }

      /**
       * Returns a new builder to build an additional value of the "Entries" property. Use {@link
       * uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes.Entry.Builder#end()}
       * to return to the current builder.
       *
       * @return a new builder to build an additional value of the "Entries" property. Use {@link
       *     uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.SampleAttributes.Entry.Builder#end()}
       *     to return to the current builder.
       */
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              ? extends
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Builder<
                      _B>>
          addEntries() {
        if (this.entries == null) {
          this.entries =
              new ArrayList<
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .SampleAttributes.Entry.Builder<
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Builder<
                          _B>>>();
        }
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry.Builder<
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Builder<
                    _B>>
            entries_Builder =
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Builder<
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Builder<
                        _B>>(this, null, false);
        this.entries.add(entries_Builder);
        return entries_Builder;
      }

      @Override
      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes
          build() {
        if (_storedValue == null) {
          return this.init(
              new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes());
        } else {
          return ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes)
              _storedValue);
        }
      }
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"key", "value"})
    public static class Entry {

      protected String key;
      protected String value;

      /** Default no-arg constructor */
      public Entry() {
        super();
      }

      /** Fully-initialising value constructor */
      public Entry(final String key, final String value) {
        this.key = key;
        this.value = value;
      }

      /**
       * Gets the value of the key property.
       *
       * @return possible object is {@link String }
       */
      public String getKey() {
        return key;
      }

      /**
       * Sets the value of the key property.
       *
       * @param value allowed object is {@link String }
       */
      public void setKey(String value) {
        this.key = value;
      }

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Copies all state of this object to a builder. This method is used by the {@link #copyOf}
       * method and should not be called directly by client code.
       *
       * @param _other A builder instance to which the state of this object will be copied.
       */
      public <_B> void copyTo(
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              _other) {
        _other.key = this.key;
        _other.value = this.value;
      }

      public <_B>
          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              newCopyBuilder(final _B _parentBuilder) {
        return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry.Builder<
            _B>(_parentBuilder, this, true);
      }

      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              Void>
          newCopyBuilder() {
        return newCopyBuilder(null);
      }

      public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              Void>
          builder() {
        return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry.Builder<
            Void>(null, null, false);
      }

      public static <_B>
          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              copyOf(
                  final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                          .SampleUnit.SampleAttributes.Entry
                      _other) {
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry.Builder<
                _B>
            _newBuilder =
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Builder<
                    _B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
      }

      /**
       * Copies all state of this object to a builder. This method is used by the {@link #copyOf}
       * method and should not be called directly by client code.
       *
       * @param _other A builder instance to which the state of this object will be copied.
       */
      public <_B> void copyTo(
          final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              _other,
          final PropertyTree _propertyTree,
          final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree keyPropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("key"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
            ? (keyPropertyTree != null)
            : ((keyPropertyTree == null) || (!keyPropertyTree.isLeaf())))) {
          _other.key = this.key;
        }
        final PropertyTree valuePropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("value"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
            ? (valuePropertyTree != null)
            : ((valuePropertyTree == null) || (!valuePropertyTree.isLeaf())))) {
          _other.value = this.value;
        }
      }

      public <_B>
          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              newCopyBuilder(
                  final _B _parentBuilder,
                  final PropertyTree _propertyTree,
                  final PropertyTreeUse _propertyTreeUse) {
        return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry.Builder<
            _B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
      }

      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              Void>
          newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
      }

      public static <_B>
          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry.Builder<
                  _B>
              copyOf(
                  final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                          .SampleUnit.SampleAttributes.Entry
                      _other,
                  final PropertyTree _propertyTree,
                  final PropertyTreeUse _propertyTreeUse) {
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry.Builder<
                _B>
            _newBuilder =
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Builder<
                    _B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
      }

      public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              Void>
          copyExcept(
              final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry
                  _other,
              final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
      }

      public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Builder<
              Void>
          copyOnly(
              final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Entry
                  _other,
              final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
      }

      public boolean equals(Object object) {
        if ((object == null) || (this.getClass() != object.getClass())) {
          return false;
        }
        if (this == object) {
          return true;
        }
        final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry
            that =
                ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry)
                    object);
        {
          String leftKey;
          leftKey = this.getKey();
          String rightKey;
          rightKey = that.getKey();
          if (this.key != null) {
            if (that.key != null) {
              if (!leftKey.equals(rightKey)) {
                return false;
              }
            } else {
              return false;
            }
          } else {
            if (that.key != null) {
              return false;
            }
          }
        }
        {
          String leftValue;
          leftValue = this.getValue();
          String rightValue;
          rightValue = that.getValue();
          if (this.value != null) {
            if (that.value != null) {
              if (!leftValue.equals(rightValue)) {
                return false;
              }
            } else {
              return false;
            }
          } else {
            if (that.value != null) {
              return false;
            }
          }
        }
        return true;
      }

      public int hashCode() {
        int currentHashCode = 1;
        {
          currentHashCode = (currentHashCode * 31);
          String theKey;
          theKey = this.getKey();
          if (this.key != null) {
            currentHashCode += theKey.hashCode();
          }
        }
        {
          currentHashCode = (currentHashCode * 31);
          String theValue;
          theValue = this.getValue();
          if (this.value != null) {
            currentHashCode += theValue.hashCode();
          }
        }
        return currentHashCode;
      }

      public static class Builder<_B> implements Buildable {

        protected final _B _parentBuilder;
        protected final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                .SampleUnit.SampleAttributes.Entry
            _storedValue;
        private String key;
        private String value;

        public Builder(
            final _B _parentBuilder,
            final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry
                _other,
            final boolean _copy) {
          this._parentBuilder = _parentBuilder;
          if (_other != null) {
            if (_copy) {
              _storedValue = null;
              this.key = _other.key;
              this.value = _other.value;
            } else {
              _storedValue = _other;
            }
          } else {
            _storedValue = null;
          }
        }

        public Builder(
            final _B _parentBuilder,
            final uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry
                _other,
            final boolean _copy,
            final PropertyTree _propertyTree,
            final PropertyTreeUse _propertyTreeUse) {
          this._parentBuilder = _parentBuilder;
          if (_other != null) {
            if (_copy) {
              _storedValue = null;
              final PropertyTree keyPropertyTree =
                  ((_propertyTree == null) ? null : _propertyTree.get("key"));
              if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                  ? (keyPropertyTree != null)
                  : ((keyPropertyTree == null) || (!keyPropertyTree.isLeaf())))) {
                this.key = _other.key;
              }
              final PropertyTree valuePropertyTree =
                  ((_propertyTree == null) ? null : _propertyTree.get("value"));
              if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                  ? (valuePropertyTree != null)
                  : ((valuePropertyTree == null) || (!valuePropertyTree.isLeaf())))) {
                this.value = _other.value;
              }
            } else {
              _storedValue = _other;
            }
          } else {
            _storedValue = null;
          }
        }

        public _B end() {
          return this._parentBuilder;
        }

        protected <
                _P extends
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Entry>
            _P init(final _P _product) {
          _product.key = this.key;
          _product.value = this.value;
          return _product;
        }

        /**
         * Sets the new value of "key" (any previous value will be replaced)
         *
         * @param key New value of the "key" property.
         */
        public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry.Builder<
                _B>
            withKey(final String key) {
          this.key = key;
          return this;
        }

        /**
         * Sets the new value of "value" (any previous value will be replaced)
         *
         * @param value New value of the "value" property.
         */
        public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry.Builder<
                _B>
            withValue(final String value) {
          this.value = value;
          return this;
        }

        @Override
        public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Entry
            build() {
          if (_storedValue == null) {
            return this.init(
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .SampleAttributes.Entry());
          } else {
            return ((uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                    .SampleUnit.SampleAttributes.Entry)
                _storedValue);
          }
        }
      }

      public static class Select
          extends uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Selector<
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Select,
              Void> {

        Select() {
          super(null, null, null);
        }

        public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                .SampleUnit.SampleAttributes.Entry.Select
            _root() {
          return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
              .SampleUnit.SampleAttributes.Entry.Select();
        }
      }

      public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
          extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

        private com.kscs.util.jaxb.Selector<
                TRoot,
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Selector<
                    TRoot, TParent>>
            key = null;
        private com.kscs.util.jaxb.Selector<
                TRoot,
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Selector<
                    TRoot, TParent>>
            value = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
          super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
          final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
          products.putAll(super.buildChildren());
          if (this.key != null) {
            products.put("key", this.key.init());
          }
          if (this.value != null) {
            products.put("value", this.value.init());
          }
          return products;
        }

        public com.kscs.util.jaxb.Selector<
                TRoot,
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Selector<
                    TRoot, TParent>>
            key() {
          return ((this.key == null)
              ? this.key =
                  new com.kscs.util.jaxb.Selector<
                      TRoot,
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Entry.Selector<
                          TRoot, TParent>>(this._root, this, "key")
              : this.key);
        }

        public com.kscs.util.jaxb.Selector<
                TRoot,
                uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Selector<
                    TRoot, TParent>>
            value() {
          return ((this.value == null)
              ? this.value =
                  new com.kscs.util.jaxb.Selector<
                      TRoot,
                      uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition
                              .SampleUnit.SampleAttributes.Entry.Selector<
                          TRoot, TParent>>(this._root, this, "value")
              : this.value);
        }
      }
    }

    public static class Select
        extends uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Selector<
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Select,
            Void> {

      Select() {
        super(null, null, null);
      }

      public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .SampleAttributes.Select
          _root() {
        return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            .SampleAttributes.Select();
      }
    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
        extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

      private uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Selector<
              TRoot,
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Selector<
                  TRoot, TParent>>
          entries = null;

      public Selector(final TRoot root, final TParent parent, final String propertyName) {
        super(root, parent, propertyName);
      }

      @Override
      public Map<String, PropertyTree> buildChildren() {
        final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
        products.putAll(super.buildChildren());
        if (this.entries != null) {
          products.put("entries", this.entries.init());
        }
        return products;
      }

      public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                  .SampleAttributes.Entry.Selector<
              TRoot,
              uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Selector<
                  TRoot, TParent>>
          entries() {
        return ((this.entries == null)
            ? this.entries =
                new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                        .SampleAttributes.Entry.Selector<
                    TRoot,
                    uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                            .SampleAttributes.Selector<
                        TRoot, TParent>>(this._root, this, "entries")
            : this.entries);
      }
    }
  }

  public static class Select
      extends uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
              .Selector<
          uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit.Select,
          Void> {

    Select() {
      super(null, null, null);
    }

    public static uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
            .Select
        _root() {
      return new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
          .Select();
    }
  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
      extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

    private com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        id = null;
    private com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleUnitRef = null;
    private com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleUnitType = null;
    private com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        formType = null;
    private com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        collectionExerciseId = null;
    private uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleAttributes = null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
      products.putAll(super.buildChildren());
      if (this.id != null) {
        products.put("id", this.id.init());
      }
      if (this.sampleUnitRef != null) {
        products.put("sampleUnitRef", this.sampleUnitRef.init());
      }
      if (this.sampleUnitType != null) {
        products.put("sampleUnitType", this.sampleUnitType.init());
      }
      if (this.formType != null) {
        products.put("formType", this.formType.init());
      }
      if (this.collectionExerciseId != null) {
        products.put("collectionExerciseId", this.collectionExerciseId.init());
      }
      if (this.sampleAttributes != null) {
        products.put("sampleAttributes", this.sampleAttributes.init());
      }
      return products;
    }

    public com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        id() {
      return ((this.id == null)
          ? this.id =
              new com.kscs.util.jaxb.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "id")
          : this.id);
    }

    public com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleUnitRef() {
      return ((this.sampleUnitRef == null)
          ? this.sampleUnitRef =
              new com.kscs.util.jaxb.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "sampleUnitRef")
          : this.sampleUnitRef);
    }

    public com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleUnitType() {
      return ((this.sampleUnitType == null)
          ? this.sampleUnitType =
              new com.kscs.util.jaxb.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "sampleUnitType")
          : this.sampleUnitType);
    }

    public com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        formType() {
      return ((this.formType == null)
          ? this.formType =
              new com.kscs.util.jaxb.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "formType")
          : this.formType);
    }

    public com.kscs.util.jaxb.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        collectionExerciseId() {
      return ((this.collectionExerciseId == null)
          ? this.collectionExerciseId =
              new com.kscs.util.jaxb.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "collectionExerciseId")
          : this.collectionExerciseId);
    }

    public uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                .SampleAttributes.Selector<
            TRoot,
            uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                    .Selector<
                TRoot, TParent>>
        sampleAttributes() {
      return ((this.sampleAttributes == null)
          ? this.sampleAttributes =
              new uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                      .SampleAttributes.Selector<
                  TRoot,
                  uk.gov.ons.ctp.response.collection.exercise.lib.sampleunit.definition.SampleUnit
                          .Selector<
                      TRoot, TParent>>(this._root, this, "sampleAttributes")
          : this.sampleAttributes);
    }
  }
}
