spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres

  liquibase:
    url: jdbc:postgresql://localhost:15432/postgres

survey-svc:
  connection-config:
    port: 18002

sample-svc:
  connection-config:
    port: 18002

collection-instrument-svc:
    connection-config:
        port: 18002

party-svc:
    connection-config:
        port: 18002

action-svc:
  connection-config:
    port: 18002

redisson-config:
  address: localhost:17379

rabbitmq:
  host: localhost
  port: 35672

gcp:
  project: "test"
  sampleDistributionTopic: "test_topic"