info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  useJson: true
  level:
    uk.gov.ons.ctp: INFO
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
  profile: CLOUD

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema: collectionexercise
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: true
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    role: SUPERUSER
    enabled: true
  health:
    mongo:
      enabled: true
    rabbit:
      enabled: false

server:
  port: 8145
  servlet-path: /

spring:
  output:
    ansi:
      enabled: never

  application:
    name: ONS CollectionExerciseSvc

  datasource:
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
    continue-on-error: true
    schema: classpath:/schema-cloud.sql
    user: ${cloud.services.postgresql.connection.username}
    password: ${cloud.services.postgresql.connection.password}
    default-schema: collectionexercise
    url: ${cloud.services.postgresql.connection.jdbcurl}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: collectionexercise

sample-svc:
  request-sample-units-path: /samples/sampleunitrequests
  connection-config:
    scheme: http
    host: localhost
    port: 8125
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 10
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

action-svc:
  action-plans-path: /actionplans
  action-rules-path: /actionrules
  action-rule-path: /actionrules/{actionRuleId}
  action-rules-for-action-plan-path: /actionrules/actionplan/{actionPlanId}
  connection-config:
    scheme: http
    host: localhost
    port: 8151
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 10
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

survey-svc:
  request-classifier-types-list-path: /surveys/{surveyId}/classifiertypeselectors
  request-classifier-types-path: /surveys/{surveyId}/classifiertypeselectors/{selectorId}
  connection-config:
    scheme: http
    host: localhost
    port: 8080
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

collection-instrument-svc:
  request-collection-instruments: /collection-instrument-api/1.0.2/collectioninstrument
  request-collection-instruments-count: /collection-instrument-api/1.0.2/collectioninstrument/count
  connection-config:
    scheme: http
    host: ras-collection-instrument-int.apps.mvp.onsclofo.uk
    port: 80
    username: admin
    password: secret
    retry-attempts: 5
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

party-svc:
  request-party-path: /party-api/v1/parties/type/{sampleUnitType}/ref/{sampleUnitRef}
  connection-config:
    scheme: http
    host: ras-party-service-int.apps.mvp.onsclofo.uk
    port: 80
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

redisson-config:
  address: ${cloud.services.redis.connection.host}:6379
  time-to-live-seconds: 300

rabbitmq:
  username: ${cloud.services.rabbitmq.connection.username}
  password: ${cloud.services.rabbitmq.connection.password}
  host: ${cloud.services.rabbitmq.connection.host}
  port: ${cloud.services.rabbitmq.connection.port}
  virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: false
  group-name: collectionexerciseservice-api
  title: Collection Exercise Service API
  description: API for ${project.artifactId}
  version: ${project.version}
