liquibase:
  url: jdbc:postgresql://localhost:15432/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres

survey-svc:
  connection-config:
    port: 18080

redisson-config:
  address: localhost:17379

rabbitmq:
  host: localhost
  port: 15672

