info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  useJson: false
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
  profile: DEV

server:
  port: 8145

spring:
  main:
    # Added as part of upgrade to 2.1 to quiet an error where the 'restExceptionHandler' bean is defined twice.
    allow-bean-definition-overriding: true

  liquibase:
    user: postgres
    password: postgres
    default-schema: collectionexercise
    url: jdbc:postgresql://localhost:5432/ras
    change-log: classpath:/database/changelog-master.yml
    enabled: false

  output:
    ansi:
      enabled: never

  management:
    endpoints:
      web:
        exposure:
          include: health,info

  security:
    user:
      name: admin
      password: secret
    
  application:
    name: ONS CollectionExerciseSvc

  # In spring boot 2.5, schema.sql isn't run on startup anymore.  Because the schema isn't created in the first liquibase
  # patch, we're overriding how it's handled so it can be created if it's not there.
  sql.init.mode: always
  sql.init.continue-on-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ras
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      default_schema: collectionexercise

    # Used to suppress warning that appeared after upgrade to spring 2.0. It defaults to true, and we weren't setting
    # it so nothing changed.  Spring boot shows warnings if you don't explicitly set it.
    open-in-view: true

  cloud:
    gcp:
      project-id: ras-rm-dev

sample-svc:
  request-sample-unit-count-path: /samples/count
  request-sample-units-for-sample-summary-path: /samples/{sampleSummaryId}/sampleunits
  connection-config:
    scheme: http
    host: localhost
    port: 8125
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

survey-svc:
  request-classifier-types-list-path: /surveys/{surveyId}/classifiertypeselectors
  request-classifier-types-path: /surveys/{surveyId}/classifiertypeselectors/{selectorId}
  survey-detail-path: /surveys/{surveyId}
  survey-ref-path: /surveys/ref/{surveyRef}
  connection-config:
    scheme: http
    host: localhost
    port: 8080
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

action-svc:
  process-event-path: /process-event
  connection-config:
    scheme: http
    host: localhost
    port: 8151
    username: admin
    password: secret

case-svc:
  number-of-cases-path: /casegroups/cases/{collectionExerciseId}/all
  process-event-path: /process-event
  connection-config:
    scheme: http
    host: localhost
    port: 8171
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 10
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

collection-instrument-svc:
  request-collection-instruments-count: /collection-instrument-api/1.0.2/collectioninstrument/count
  connection-config:
    scheme: http
    host: localhost
    port: 8002
    username: admin
    password: secret
    retry-attempts: 5
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

redisson-config:
  address: localhost:6379
  list-time-to-live-seconds: 300
  list-time-to-wait-seconds: 300

schedules:
  # number retrieved for each collection exercise each run, distributes this number for each exercise
  distribution-schedule-retrieval-max: 1000

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: true
  group-name: collectionexerciseservice-api
  title: Collection Exercise Service API
  description: API for ${project.artifactId}
  version: ${project.version}

springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /api-doc.html
    operationsSorter: method
    enabled: false

gcp:
  project: ras-rm-sandbox
  caseNotificationTopic: "test_topic"
  sampleSummaryActivationStatusSubscription: "sample-summary-activation-status"
  sampleSummaryActivationTopic: "sample-summary-activation"
  collectionExerciseEndTopic: "collect-exercise-end"
  collectionExerciseEventStatusUpdateSubscription: "event_status_subscription"
