liquibase:
  url: jdbc:postgresql://localhost:15432/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres

survey-svc:
  connection-config:
    port: 18080

action-svc:
  connection-config:
    port: 38151

redisson-config:
  address: localhost:17379

rabbitmq:
  host: localhost
  port: 15672

schedules:
  validation-schedule-delay-milli-seconds: 5000
  distribution-schedule-delay-milli-seconds: 5000

collection-instrument-svc:
    connection-config:
        port: 18002

party-svc:
    connection-config:
        port: 18002

