liquibase:
  url: jdbc:postgresql://localhost:15432/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
  zipkin:
    baseUrl: http://nervous_chebyshev:9411

survey-svc:
  connection-config:
    port: 18002

sample-svc:
  connection-config:
    port: 18002

collection-instrument-svc:
    connection-config:
        port: 18002

party-svc:
    connection-config:
        port: 18002

action-svc:
  connection-config:
    port: 18002

redisson-config:
  address: localhost:17379

rabbitmq:
  host: localhost
  port: 35672

schedules:
  validation-schedule-delay-milli-seconds: 5000
  distribution-schedule-delay-milli-seconds: 5000

