spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres

  liquibase:
    url: jdbc:postgresql://localhost:15432/postgres

  cloud:
    gcp:
      project-id: test
      pubsub:
        emulator-host: localhost:18681

survey-svc:
  connection-config:
    port: 18002

sample-svc:
  connection-config:
    port: 18002

collection-instrument-svc:
    connection-config:
        port: 18002

party-svc:
    connection-config:
        port: 18002

redisson-config:
  address: localhost:17379

gcp:
  project: "test"
  caseNotificationTopic: "test_topic"