info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  useJson: false
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
  profile: DEV

liquibase:
  user: postgres
  password: postgres
  default-schema: collectionexercise
  url: jdbc:postgresql://localhost:6432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: true
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    role: SUPERUSER
    enabled: true
  health:
    mongo:
      enabled: true
    rabbit:
      enabled: false

server:
  port: 8145
  servlet-path: /

endpoints:
  info:
    enabled: true
    sensitive: false
  enabled: true

spring:
  output:
    ansi:
      enabled: never
    
  application:
    name: ONS CollectionExerciseSvc

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: collectionexercise

sample-svc:
  request-sample-units-path: /samples/sampleunitrequests
  request-sample-unit-count-path: /samples/count
  connection-config:
    scheme: http
    host: localhost
    port: 8125
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

survey-svc:
  request-classifier-types-list-path: /surveys/{surveyId}/classifiertypeselectors
  request-classifier-types-path: /surveys/{surveyId}/classifiertypeselectors/{selectorId}
  survey-detail-path: /surveys/{surveyId}
  survey-ref-path: /surveys/ref/{surveyRef}
  connection-config:
    scheme: http
    host: localhost
    port: 8080
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

action-svc:
  deprecated: false
  action-plans-path: /actionplans
  action-plan-path: /actionplans/{actionPlanId}
  action-rules-path: /actionrules
  action-rule-path: /actionrules/{actionRuleId}
  action-rules-for-action-plan-path: /actionrules/actionplan/{actionPlanId}
  connection-config:
    scheme: http
    host: localhost
    port: 8151
    username: admin
    password: secret

case-svc:
  execute-events-path: /execute-event
  connection-config:
    scheme: http
    host: localhost
    port: 8171
    username: admin
    password: secret

collection-instrument-svc:
  request-collection-instruments: /collection-instrument-api/1.0.2/collectioninstrument
  request-collection-instruments-count: /collection-instrument-api/1.0.2/collectioninstrument/count
  connection-config:
    scheme: http
    host: localhost
    port: 8002
    username: admin
    password: secret
    retry-attempts: 5
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

party-svc:
  request-party-path: /party-api/v1/parties/type/{sampleUnitType}/ref/{sampleUnitRef}
  sample-link-path: /party-api/v1/businesses/sample/link/{sampleSummaryId}
  connection-config:
    scheme: http
    host: localhost
    port: 8081
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

redisson-config:
  address: localhost:7379
  list-time-to-live-seconds: 300
  list-time-to-wait-seconds: 300

schedules:
  # number retrieved for each collection exercise each run, distributes this number for each exercise
  distribution-schedule-retrieval-max: 1000

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: true
  group-name: collectionexerciseservice-api
  title: Collection Exercise Service API
  description: API for ${project.artifactId}
  version: ${project.version}

springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /api-doc.html
    operationsSorter: method
    enabled: false