info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
  profile: DEV

liquibase:
  user: collectionexercisesvc
  password: collectionexercisesvc
  default-schema: collectionexercise
  url: jdbc:postgresql://localhost:5432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: collectionexercise
    password: ctp

management:
  security:
    role: SUPERUSER
    enabled: true
  health:
    mongo:
      enabled: true
    rabbit:
      enabled: false

server:
  port: 8145
  servlet-path: /

endpoints:
  autoconfig:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  output:
    ansi:
      enabled: never

  application:
    name: ONS CollectionExerciseSvc

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: collectionexercisesvc
    password: collectionexercisesvc
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: collectionexercise

  sleuth:
    sampler:
      percentage: 10

  zipkin:
    enabled: false

sample-svc:
  request-sample-units-path: /samples/sampleunitrequests
  connection-config:
    scheme: http
    host: localhost
    port: 8125
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

survey-svc:
  request-classifier-types-list-path: /surveys/{surveyId}/classifiertypeselectors
  request-classifier-types-path: /surveys/{surveyId}/classifiertypeselectors/{selectorId}
  connection-config:
    scheme: http
    host: localhost
    port: 8080
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000
    
collection-instrument-svc:
  request-collection-instruments: /collection-instrument-api/1.0.2/collectioninstrument
  connection-config:
    scheme: http
    host: ras-collection-instrument-int.apps.devtest.onsclofo.uk
    port: 80
    retry-attempts: 5
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

party-svc:
  request-party-path: /party-api/v1/parties/type/{sampleUnitType}/ref/{sampleUnitRef}
  connection-config:
    scheme: http
    host: ras-party-service-int.apps.devtest.onsclofo.uk
    port: 80
    # how many times should we attempt connection on failure
    retry-attempts: 5
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

redisson-config:
  address: localhost:6379

schedules:
  validation-schedule-delay-milli-seconds: 5000
  validation-schedule-retrieval-max: 10000
  distribution-schedule-delay-milli-seconds: 10000
  distribution-schedule-retrieval-max: 10000

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  virtualhost: /

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: true
  group-name: "collectionexerciseservice-api"
  title: "Collection Exercise Service API"
  description: "API for the Collection Exercise Service"
  version: "10.41"