apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-server
              containerPort: {{ .Values.container.port }}
          readinessProbe:
            httpGet:
              path: /info
              port: {{ .Values.container.port }}
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /info
              port: {{ .Values.container.port }}
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          {{- .Values.databaseConfig | nindent 10 -}}
          - name: SECURITY_USER_NAME
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-user
          - name: SECURITY_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-password
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          - name: SERVER_PORT
            value: "{{ .Valeus.container.port }}"
          - name: SECURITY_BASIC_ENABLED
            value: "true"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          - name: LIQUIBASE_URL
            value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          - name: RABBITMQ_HOST
            value: "$(RABBITMQ_SERVICE_HOST)"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: REDISSON_CONFIG_ADDRESS
            value: "$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)"
          - name: DATA_GRID_ADDRESS
            value: "$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)"
          - name: ACTION_SVC_CONNECTION_CONFIG_HOST
            value: "$(ACTION_SERVICE_HOST)"
          - name: ACTION_SVC_CONNECTION_CONFIG_PORT
            value: "$(ACTION_SERVICE_PORT)"
          - name: SAMPLE_SVC_CONNECTION_CONFIG_HOST
            value: "$(SAMPLE_SERVICE_HOST)"
          - name: SAMPLE_SVC_CONNECTION_CONFIG_PORT
            value: "$(SAMPLE_SERVICE_PORT)"
          - name: SURVEY_SVC_CONNECTION_CONFIG_HOST
            value: "$(SURVEY_SERVICE_HOST)"
          - name: SURVEY_SVC_CONNECTION_CONFIG_PORT
            value: "$(SURVEY_SERVICE_PORT)"
          - name: PARTY_SVC_CONNECTION_CONFIG_HOST
            value: "$(PARTY_SERVICE_HOST)"
          - name: PARTY_SVC_CONNECTION_CONFIG_PORT
            value: "$(PARTY_SERVICE_PORT)"
          - name: PARTY_SVC_CONNECTION_CONFIG_USERNAME
            value: "$(SECURITY_USER_NAME)"
          - name: PARTY_SVC_CONNECTION_CONFIG_PASSWORD
            value: "$(SECURITY_USER_PASSWORD)"
          - name: COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_HOST
            value: "$(COLLECTION_INSTRUMENT_SERVICE_HOST)"
          - name: COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PORT
            value: "$(COLLECTION_INSTRUMENT_SERVICE_PORT)"
          - name: COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_USERNAME
            value: "$(SECURITY_USER_NAME)"
          - name: COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PASSWORD
            value: "$(SECURITY_USER_PASSWORD)"
          - name: SCHEDULES_VALIDATION_SCHEDULE_DELAY_MILLI_SECONDS
            value: "1000"
          - name: SCHEDULES_DISTRIBUTION_SCHEDULE_DELAY_MILLI_SECONDS
            value: "1000"
          - name: LIQUIBASE_USER
            value: "$(DB_USERNAME)"
          - name: LIQUIBASE_PASSWORD
            value: "$(DB_PASSWORD)"
          - name: SPRING_DATASOURCE_USERNAME
            value: "$(DB_USERNAME)"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "$(DB_PASSWORD)"
          - name: SPRING_ZIPKIN_ENABLED
            value: "true"
          - name: SPRING_ZIPKIN_BASEURL
            value: "http://$(ZIPKIN_SERVICE_HOST):$(ZIPKIN_SERVICE_PORT)/"
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
