apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
