@startuml
skinparam state {
    BackgroundColor HoneyDew
    BackgroundColor<<New>> MistyRose
    BackgroundColor<<Changed>> PaleTurquoise
}
skinparam note {
    BackgroundColor<<New>> MistyRose
    BackgroundColor<<Changed>> PaleTurquoise
}

[*] --> CREATED
note left of CREATED : this used to be INIT
CREATED<<Changed>> --> CREATED : ci_sample_added
CREATED<<Changed>> --> CREATED : ci_sample_deleted
CREATED<<Changed>> --> CREATED : events_deleted
CREATED<<Changed>> --> SCHEDULED : events_added
note left #MistyRose
   states this colour are new
end note
CREATED --> EXECUTION_STARTED : execute
SCHEDULED<<New>> --> SCHEDULED : events_added
SCHEDULED<<New>> --> SCHEDULED : ci_sample_deleted
SCHEDULED<<New>> --> READY_FOR_REVIEW : ci_sample_added
READY_FOR_REVIEW<<New>> --> SCHEDULED : ci_sample_deleted
READY_FOR_REVIEW<<New>> --> CREATED : events_deleted
SCHEDULED<<New>> --> CREATED : events_deleted
READY_FOR_REVIEW<<New>> --> EXECUTION_STARTED : execute
EXECUTION_STARTED<<Changed>> --> EXECUTION_STARTED : execute
note left of EXECUTION_STARTED : this used to be PENDING
EXECUTION_STARTED --> EXECUTED : execution_complete
EXECUTED --> VALIDATED : validate
EXECUTED --> FAILEDVALIDATION : invalidate
VALIDATED --> READY_FOR_LIVE<<Changed>> : publish
note left of READY_FOR_LIVE: this used to be PUBLISHED
note right of READY_FOR_LIVE #PaleTurquoise
    states this colour have been renamed
end note
READY_FOR_LIVE --> LIVE<<New>> : go_live
FAILEDVALIDATION --> EXECUTION_STARTED : execute
@enduml