package uk.gov.ons.ctp.response.collection.exercise.lib.common.redis;

import static net.logstash.logback.argument.StructuredArguments.kv;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class EndpointCacheDataDeleter {
  /**
   * This key was generated by caching the result of
   * /collectionexercises/survey/{survey_id}?liveOnly=true in frontstage
   */
  private static final Logger log = LoggerFactory.getLogger(EndpointCacheDataDeleter.class);

  private static final String REDIS_KEY_PREFIX = "frontstage:collection-exercise-by-survey-id:";

  @Autowired private RedisUtil<Object> redisUtil;

  // catch exception to prevent errors from redis preventing go live
  public void deleteFrontstageExerciseByIdKey(String surveyId) {
    String key = REDIS_KEY_PREFIX + surveyId;
    try {
      Boolean cacheInvalidated = redisUtil.deleteValue(key);
      log.info("Cache invalidated with key", kv("key", key), kv("success", cacheInvalidated));
    } catch (Exception e) {
      log.error("Unable to remove key from redis", kv("key", key), e);
    }
  }
}
